[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "create-react-app"
  targetPort = 3000

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 